// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/waddle_protocol.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WaddleRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Operation:
	//
	//	*WaddleRequest_CheckKey
	//	*WaddleRequest_GetVal
	//	*WaddleRequest_GetLen
	//	*WaddleRequest_GetLast
	//	*WaddleRequest_AddVal
	//	*WaddleRequest_SearchGlobal
	//	*WaddleRequest_SearchKey
	//	*WaddleRequest_Snapshot
	//	*WaddleRequest_UpdateVal
	//	*WaddleRequest_GetKeys
	//	*WaddleRequest_GetValList
	Operation     isWaddleRequest_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaddleRequest) Reset() {
	*x = WaddleRequest{}
	mi := &file_proto_waddle_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaddleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaddleRequest) ProtoMessage() {}

func (x *WaddleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_waddle_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaddleRequest.ProtoReflect.Descriptor instead.
func (*WaddleRequest) Descriptor() ([]byte, []int) {
	return file_proto_waddle_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *WaddleRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WaddleRequest) GetOperation() isWaddleRequest_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *WaddleRequest) GetCheckKey() *CheckKeyRequest {
	if x != nil {
		if x, ok := x.Operation.(*WaddleRequest_CheckKey); ok {
			return x.CheckKey
		}
	}
	return nil
}

func (x *WaddleRequest) GetGetVal() *GetValueByIndexRequest {
	if x != nil {
		if x, ok := x.Operation.(*WaddleRequest_GetVal); ok {
			return x.GetVal
		}
	}
	return nil
}

func (x *WaddleRequest) GetGetLen() *GetLengthRequest {
	if x != nil {
		if x, ok := x.Operation.(*WaddleRequest_GetLen); ok {
			return x.GetLen
		}
	}
	return nil
}

func (x *WaddleRequest) GetGetLast() *GetLastValueRequest {
	if x != nil {
		if x, ok := x.Operation.(*WaddleRequest_GetLast); ok {
			return x.GetLast
		}
	}
	return nil
}

func (x *WaddleRequest) GetAddVal() *AddValueRequest {
	if x != nil {
		if x, ok := x.Operation.(*WaddleRequest_AddVal); ok {
			return x.AddVal
		}
	}
	return nil
}

func (x *WaddleRequest) GetSearchGlobal() *SearchGlobalRequest {
	if x != nil {
		if x, ok := x.Operation.(*WaddleRequest_SearchGlobal); ok {
			return x.SearchGlobal
		}
	}
	return nil
}

func (x *WaddleRequest) GetSearchKey() *SearchOnKeyRequest {
	if x != nil {
		if x, ok := x.Operation.(*WaddleRequest_SearchKey); ok {
			return x.SearchKey
		}
	}
	return nil
}

func (x *WaddleRequest) GetSnapshot() *SnapshotRequest {
	if x != nil {
		if x, ok := x.Operation.(*WaddleRequest_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *WaddleRequest) GetUpdateVal() *UpdateValueRequest {
	if x != nil {
		if x, ok := x.Operation.(*WaddleRequest_UpdateVal); ok {
			return x.UpdateVal
		}
	}
	return nil
}

func (x *WaddleRequest) GetGetKeys() *GetKeysRequest {
	if x != nil {
		if x, ok := x.Operation.(*WaddleRequest_GetKeys); ok {
			return x.GetKeys
		}
	}
	return nil
}

func (x *WaddleRequest) GetGetValList() *GetValueListRequest {
	if x != nil {
		if x, ok := x.Operation.(*WaddleRequest_GetValList); ok {
			return x.GetValList
		}
	}
	return nil
}

type isWaddleRequest_Operation interface {
	isWaddleRequest_Operation()
}

type WaddleRequest_CheckKey struct {
	CheckKey *CheckKeyRequest `protobuf:"bytes,2,opt,name=check_key,json=checkKey,proto3,oneof"` // 1. check_key(key)
}

type WaddleRequest_GetVal struct {
	GetVal *GetValueByIndexRequest `protobuf:"bytes,3,opt,name=get_val,json=getVal,proto3,oneof"` // 2. get_value_by_index(key, index)
}

type WaddleRequest_GetLen struct {
	GetLen *GetLengthRequest `protobuf:"bytes,4,opt,name=get_len,json=getLen,proto3,oneof"` // 3. get_length(key)
}

type WaddleRequest_GetLast struct {
	GetLast *GetLastValueRequest `protobuf:"bytes,5,opt,name=get_last,json=getLast,proto3,oneof"` // 4. get_last_value(key)
}

type WaddleRequest_AddVal struct {
	AddVal *AddValueRequest `protobuf:"bytes,6,opt,name=add_val,json=addVal,proto3,oneof"` // 5. add_value(key, value)
}

type WaddleRequest_SearchGlobal struct {
	SearchGlobal *SearchGlobalRequest `protobuf:"bytes,8,opt,name=search_global,json=searchGlobal,proto3,oneof"` // 6. search_global(search_param)
}

type WaddleRequest_SearchKey struct {
	SearchKey *SearchOnKeyRequest `protobuf:"bytes,9,opt,name=search_key,json=searchKey,proto3,oneof"` // 7. search_on_key(key, value)
}

type WaddleRequest_Snapshot struct {
	Snapshot *SnapshotRequest `protobuf:"bytes,10,opt,name=snapshot,proto3,oneof"` // 8. snapshot()
}

type WaddleRequest_UpdateVal struct {
	UpdateVal *UpdateValueRequest `protobuf:"bytes,7,opt,name=update_val,json=updateVal,proto3,oneof"` // 9. update_value(key, index, value)
}

type WaddleRequest_GetKeys struct {
	GetKeys *GetKeysRequest `protobuf:"bytes,11,opt,name=get_keys,json=getKeys,proto3,oneof"` // 10. get_keys()
}

type WaddleRequest_GetValList struct {
	GetValList *GetValueListRequest `protobuf:"bytes,12,opt,name=get_val_list,json=getValList,proto3,oneof"` // 11. get_value_list(key)
}

func (*WaddleRequest_CheckKey) isWaddleRequest_Operation() {}

func (*WaddleRequest_GetVal) isWaddleRequest_Operation() {}

func (*WaddleRequest_GetLen) isWaddleRequest_Operation() {}

func (*WaddleRequest_GetLast) isWaddleRequest_Operation() {}

func (*WaddleRequest_AddVal) isWaddleRequest_Operation() {}

func (*WaddleRequest_SearchGlobal) isWaddleRequest_Operation() {}

func (*WaddleRequest_SearchKey) isWaddleRequest_Operation() {}

func (*WaddleRequest_Snapshot) isWaddleRequest_Operation() {}

func (*WaddleRequest_UpdateVal) isWaddleRequest_Operation() {}

func (*WaddleRequest_GetKeys) isWaddleRequest_Operation() {}

func (*WaddleRequest_GetValList) isWaddleRequest_Operation() {}

type WaddleResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	RequestId    string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success      bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*WaddleResponse_Item
	//	*WaddleResponse_Length
	//	*WaddleResponse_SearchResults
	//	*WaddleResponse_KeyList
	//	*WaddleResponse_ValueList
	Result        isWaddleResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaddleResponse) Reset() {
	*x = WaddleResponse{}
	mi := &file_proto_waddle_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaddleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaddleResponse) ProtoMessage() {}

func (x *WaddleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_waddle_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaddleResponse.ProtoReflect.Descriptor instead.
func (*WaddleResponse) Descriptor() ([]byte, []int) {
	return file_proto_waddle_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *WaddleResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WaddleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WaddleResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *WaddleResponse) GetResult() isWaddleResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *WaddleResponse) GetItem() *DataItem {
	if x != nil {
		if x, ok := x.Result.(*WaddleResponse_Item); ok {
			return x.Item
		}
	}
	return nil
}

func (x *WaddleResponse) GetLength() uint64 {
	if x != nil {
		if x, ok := x.Result.(*WaddleResponse_Length); ok {
			return x.Length
		}
	}
	return 0
}

func (x *WaddleResponse) GetSearchResults() *SearchResult {
	if x != nil {
		if x, ok := x.Result.(*WaddleResponse_SearchResults); ok {
			return x.SearchResults
		}
	}
	return nil
}

func (x *WaddleResponse) GetKeyList() *KeyList {
	if x != nil {
		if x, ok := x.Result.(*WaddleResponse_KeyList); ok {
			return x.KeyList
		}
	}
	return nil
}

func (x *WaddleResponse) GetValueList() *ValueList {
	if x != nil {
		if x, ok := x.Result.(*WaddleResponse_ValueList); ok {
			return x.ValueList
		}
	}
	return nil
}

type isWaddleResponse_Result interface {
	isWaddleResponse_Result()
}

type WaddleResponse_Item struct {
	Item *DataItem `protobuf:"bytes,4,opt,name=item,proto3,oneof"`
}

type WaddleResponse_Length struct {
	Length uint64 `protobuf:"varint,5,opt,name=length,proto3,oneof"`
}

type WaddleResponse_SearchResults struct {
	SearchResults *SearchResult `protobuf:"bytes,6,opt,name=search_results,json=searchResults,proto3,oneof"`
}

type WaddleResponse_KeyList struct {
	KeyList *KeyList `protobuf:"bytes,7,opt,name=key_list,json=keyList,proto3,oneof"`
}

type WaddleResponse_ValueList struct {
	ValueList *ValueList `protobuf:"bytes,8,opt,name=value_list,json=valueList,proto3,oneof"`
}

func (*WaddleResponse_Item) isWaddleResponse_Result() {}

func (*WaddleResponse_Length) isWaddleResponse_Result() {}

func (*WaddleResponse_SearchResults) isWaddleResponse_Result() {}

func (*WaddleResponse_KeyList) isWaddleResponse_Result() {}

func (*WaddleResponse_ValueList) isWaddleResponse_Result() {}

type DataItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataItem) Reset() {
	*x = DataItem{}
	mi := &file_proto_waddle_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataItem) ProtoMessage() {}

func (x *DataItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_waddle_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataItem.ProtoReflect.Descriptor instead.
func (*DataItem) Descriptor() ([]byte, []int) {
	return file_proto_waddle_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *DataItem) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DataItem) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DataItem) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CheckKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckKeyRequest) Reset() {
	*x = CheckKeyRequest{}
	mi := &file_proto_waddle_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckKeyRequest) ProtoMessage() {}

func (x *CheckKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_waddle_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckKeyRequest.ProtoReflect.Descriptor instead.
func (*CheckKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_waddle_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *CheckKeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetValueByIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValueByIndexRequest) Reset() {
	*x = GetValueByIndexRequest{}
	mi := &file_proto_waddle_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValueByIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueByIndexRequest) ProtoMessage() {}

func (x *GetValueByIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_waddle_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueByIndexRequest.ProtoReflect.Descriptor instead.
func (*GetValueByIndexRequest) Descriptor() ([]byte, []int) {
	return file_proto_waddle_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *GetValueByIndexRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetValueByIndexRequest) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

type GetLengthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLengthRequest) Reset() {
	*x = GetLengthRequest{}
	mi := &file_proto_waddle_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLengthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLengthRequest) ProtoMessage() {}

func (x *GetLengthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_waddle_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLengthRequest.ProtoReflect.Descriptor instead.
func (*GetLengthRequest) Descriptor() ([]byte, []int) {
	return file_proto_waddle_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *GetLengthRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetLastValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastValueRequest) Reset() {
	*x = GetLastValueRequest{}
	mi := &file_proto_waddle_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastValueRequest) ProtoMessage() {}

func (x *GetLastValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_waddle_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastValueRequest.ProtoReflect.Descriptor instead.
func (*GetLastValueRequest) Descriptor() ([]byte, []int) {
	return file_proto_waddle_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *GetLastValueRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type AddValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Item          *DataItem              `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddValueRequest) Reset() {
	*x = AddValueRequest{}
	mi := &file_proto_waddle_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddValueRequest) ProtoMessage() {}

func (x *AddValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_waddle_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddValueRequest.ProtoReflect.Descriptor instead.
func (*AddValueRequest) Descriptor() ([]byte, []int) {
	return file_proto_waddle_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *AddValueRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AddValueRequest) GetItem() *DataItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type UpdateValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Item          *DataItem              `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateValueRequest) Reset() {
	*x = UpdateValueRequest{}
	mi := &file_proto_waddle_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateValueRequest) ProtoMessage() {}

func (x *UpdateValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_waddle_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateValueRequest.ProtoReflect.Descriptor instead.
func (*UpdateValueRequest) Descriptor() ([]byte, []int) {
	return file_proto_waddle_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateValueRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpdateValueRequest) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *UpdateValueRequest) GetItem() *DataItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type SearchGlobalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       []byte                 `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchGlobalRequest) Reset() {
	*x = SearchGlobalRequest{}
	mi := &file_proto_waddle_protocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchGlobalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGlobalRequest) ProtoMessage() {}

func (x *SearchGlobalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_waddle_protocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGlobalRequest.ProtoReflect.Descriptor instead.
func (*SearchGlobalRequest) Descriptor() ([]byte, []int) {
	return file_proto_waddle_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *SearchGlobalRequest) GetPattern() []byte {
	if x != nil {
		return x.Pattern
	}
	return nil
}

type SearchOnKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Pattern       []byte                 `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchOnKeyRequest) Reset() {
	*x = SearchOnKeyRequest{}
	mi := &file_proto_waddle_protocol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchOnKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchOnKeyRequest) ProtoMessage() {}

func (x *SearchOnKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_waddle_protocol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchOnKeyRequest.ProtoReflect.Descriptor instead.
func (*SearchOnKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_waddle_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *SearchOnKeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SearchOnKeyRequest) GetPattern() []byte {
	if x != nil {
		return x.Pattern
	}
	return nil
}

type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotName  string                 `protobuf:"bytes,1,opt,name=snapshot_name,json=snapshotName,proto3" json:"snapshot_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_proto_waddle_protocol_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_waddle_protocol_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_waddle_protocol_proto_rawDescGZIP(), []int{11}
}

func (x *SnapshotRequest) GetSnapshotName() string {
	if x != nil {
		return x.SnapshotName
	}
	return ""
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DataItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_proto_waddle_protocol_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_waddle_protocol_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_proto_waddle_protocol_proto_rawDescGZIP(), []int{12}
}

func (x *SearchResult) GetItems() []*DataItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeysRequest) Reset() {
	*x = GetKeysRequest{}
	mi := &file_proto_waddle_protocol_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeysRequest) ProtoMessage() {}

func (x *GetKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_waddle_protocol_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeysRequest.ProtoReflect.Descriptor instead.
func (*GetKeysRequest) Descriptor() ([]byte, []int) {
	return file_proto_waddle_protocol_proto_rawDescGZIP(), []int{13}
}

type KeyList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyList) Reset() {
	*x = KeyList{}
	mi := &file_proto_waddle_protocol_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyList) ProtoMessage() {}

func (x *KeyList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_waddle_protocol_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyList.ProtoReflect.Descriptor instead.
func (*KeyList) Descriptor() ([]byte, []int) {
	return file_proto_waddle_protocol_proto_rawDescGZIP(), []int{14}
}

func (x *KeyList) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type GetValueListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValueListRequest) Reset() {
	*x = GetValueListRequest{}
	mi := &file_proto_waddle_protocol_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValueListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueListRequest) ProtoMessage() {}

func (x *GetValueListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_waddle_protocol_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueListRequest.ProtoReflect.Descriptor instead.
func (*GetValueListRequest) Descriptor() ([]byte, []int) {
	return file_proto_waddle_protocol_proto_rawDescGZIP(), []int{15}
}

func (x *GetValueListRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ValueList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DataItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueList) Reset() {
	*x = ValueList{}
	mi := &file_proto_waddle_protocol_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueList) ProtoMessage() {}

func (x *ValueList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_waddle_protocol_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueList.ProtoReflect.Descriptor instead.
func (*ValueList) Descriptor() ([]byte, []int) {
	return file_proto_waddle_protocol_proto_rawDescGZIP(), []int{16}
}

func (x *ValueList) GetItems() []*DataItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_waddle_protocol_proto protoreflect.FileDescriptor

const file_proto_waddle_protocol_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/waddle_protocol.proto\x12\twaddlemap\"\xdd\x05\n" +
	"\rWaddleRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x129\n" +
	"\tcheck_key\x18\x02 \x01(\v2\x1a.waddlemap.CheckKeyRequestH\x00R\bcheckKey\x12<\n" +
	"\aget_val\x18\x03 \x01(\v2!.waddlemap.GetValueByIndexRequestH\x00R\x06getVal\x126\n" +
	"\aget_len\x18\x04 \x01(\v2\x1b.waddlemap.GetLengthRequestH\x00R\x06getLen\x12;\n" +
	"\bget_last\x18\x05 \x01(\v2\x1e.waddlemap.GetLastValueRequestH\x00R\agetLast\x125\n" +
	"\aadd_val\x18\x06 \x01(\v2\x1a.waddlemap.AddValueRequestH\x00R\x06addVal\x12E\n" +
	"\rsearch_global\x18\b \x01(\v2\x1e.waddlemap.SearchGlobalRequestH\x00R\fsearchGlobal\x12>\n" +
	"\n" +
	"search_key\x18\t \x01(\v2\x1d.waddlemap.SearchOnKeyRequestH\x00R\tsearchKey\x128\n" +
	"\bsnapshot\x18\n" +
	" \x01(\v2\x1a.waddlemap.SnapshotRequestH\x00R\bsnapshot\x12>\n" +
	"\n" +
	"update_val\x18\a \x01(\v2\x1d.waddlemap.UpdateValueRequestH\x00R\tupdateVal\x126\n" +
	"\bget_keys\x18\v \x01(\v2\x19.waddlemap.GetKeysRequestH\x00R\agetKeys\x12B\n" +
	"\fget_val_list\x18\f \x01(\v2\x1e.waddlemap.GetValueListRequestH\x00R\n" +
	"getValListB\v\n" +
	"\toperation\"\xe7\x02\n" +
	"\x0eWaddleResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12)\n" +
	"\x04item\x18\x04 \x01(\v2\x13.waddlemap.DataItemH\x00R\x04item\x12\x18\n" +
	"\x06length\x18\x05 \x01(\x04H\x00R\x06length\x12@\n" +
	"\x0esearch_results\x18\x06 \x01(\v2\x17.waddlemap.SearchResultH\x00R\rsearchResults\x12/\n" +
	"\bkey_list\x18\a \x01(\v2\x12.waddlemap.KeyListH\x00R\akeyList\x125\n" +
	"\n" +
	"value_list\x18\b \x01(\v2\x14.waddlemap.ValueListH\x00R\tvalueListB\b\n" +
	"\x06result\"R\n" +
	"\bDataItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"#\n" +
	"\x0fCheckKeyRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"@\n" +
	"\x16GetValueByIndexRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\"$\n" +
	"\x10GetLengthRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"'\n" +
	"\x13GetLastValueRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"L\n" +
	"\x0fAddValueRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x04item\x18\x02 \x01(\v2\x13.waddlemap.DataItemR\x04item\"e\n" +
	"\x12UpdateValueRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12'\n" +
	"\x04item\x18\x03 \x01(\v2\x13.waddlemap.DataItemR\x04item\"/\n" +
	"\x13SearchGlobalRequest\x12\x18\n" +
	"\apattern\x18\x01 \x01(\fR\apattern\"@\n" +
	"\x12SearchOnKeyRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\apattern\x18\x02 \x01(\fR\apattern\"6\n" +
	"\x0fSnapshotRequest\x12#\n" +
	"\rsnapshot_name\x18\x01 \x01(\tR\fsnapshotName\"9\n" +
	"\fSearchResult\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.waddlemap.DataItemR\x05items\"\x10\n" +
	"\x0eGetKeysRequest\"\x1d\n" +
	"\aKeyList\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"'\n" +
	"\x13GetValueListRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"6\n" +
	"\tValueList\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.waddlemap.DataItemR\x05items2O\n" +
	"\rWaddleService\x12>\n" +
	"\aExecute\x12\x18.waddlemap.WaddleRequest\x1a\x19.waddlemap.WaddleResponseB\x11Z\x0fwaddlemap/protob\x06proto3"

var (
	file_proto_waddle_protocol_proto_rawDescOnce sync.Once
	file_proto_waddle_protocol_proto_rawDescData []byte
)

func file_proto_waddle_protocol_proto_rawDescGZIP() []byte {
	file_proto_waddle_protocol_proto_rawDescOnce.Do(func() {
		file_proto_waddle_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_waddle_protocol_proto_rawDesc), len(file_proto_waddle_protocol_proto_rawDesc)))
	})
	return file_proto_waddle_protocol_proto_rawDescData
}

var file_proto_waddle_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_waddle_protocol_proto_goTypes = []any{
	(*WaddleRequest)(nil),          // 0: waddlemap.WaddleRequest
	(*WaddleResponse)(nil),         // 1: waddlemap.WaddleResponse
	(*DataItem)(nil),               // 2: waddlemap.DataItem
	(*CheckKeyRequest)(nil),        // 3: waddlemap.CheckKeyRequest
	(*GetValueByIndexRequest)(nil), // 4: waddlemap.GetValueByIndexRequest
	(*GetLengthRequest)(nil),       // 5: waddlemap.GetLengthRequest
	(*GetLastValueRequest)(nil),    // 6: waddlemap.GetLastValueRequest
	(*AddValueRequest)(nil),        // 7: waddlemap.AddValueRequest
	(*UpdateValueRequest)(nil),     // 8: waddlemap.UpdateValueRequest
	(*SearchGlobalRequest)(nil),    // 9: waddlemap.SearchGlobalRequest
	(*SearchOnKeyRequest)(nil),     // 10: waddlemap.SearchOnKeyRequest
	(*SnapshotRequest)(nil),        // 11: waddlemap.SnapshotRequest
	(*SearchResult)(nil),           // 12: waddlemap.SearchResult
	(*GetKeysRequest)(nil),         // 13: waddlemap.GetKeysRequest
	(*KeyList)(nil),                // 14: waddlemap.KeyList
	(*GetValueListRequest)(nil),    // 15: waddlemap.GetValueListRequest
	(*ValueList)(nil),              // 16: waddlemap.ValueList
}
var file_proto_waddle_protocol_proto_depIdxs = []int32{
	3,  // 0: waddlemap.WaddleRequest.check_key:type_name -> waddlemap.CheckKeyRequest
	4,  // 1: waddlemap.WaddleRequest.get_val:type_name -> waddlemap.GetValueByIndexRequest
	5,  // 2: waddlemap.WaddleRequest.get_len:type_name -> waddlemap.GetLengthRequest
	6,  // 3: waddlemap.WaddleRequest.get_last:type_name -> waddlemap.GetLastValueRequest
	7,  // 4: waddlemap.WaddleRequest.add_val:type_name -> waddlemap.AddValueRequest
	9,  // 5: waddlemap.WaddleRequest.search_global:type_name -> waddlemap.SearchGlobalRequest
	10, // 6: waddlemap.WaddleRequest.search_key:type_name -> waddlemap.SearchOnKeyRequest
	11, // 7: waddlemap.WaddleRequest.snapshot:type_name -> waddlemap.SnapshotRequest
	8,  // 8: waddlemap.WaddleRequest.update_val:type_name -> waddlemap.UpdateValueRequest
	13, // 9: waddlemap.WaddleRequest.get_keys:type_name -> waddlemap.GetKeysRequest
	15, // 10: waddlemap.WaddleRequest.get_val_list:type_name -> waddlemap.GetValueListRequest
	2,  // 11: waddlemap.WaddleResponse.item:type_name -> waddlemap.DataItem
	12, // 12: waddlemap.WaddleResponse.search_results:type_name -> waddlemap.SearchResult
	14, // 13: waddlemap.WaddleResponse.key_list:type_name -> waddlemap.KeyList
	16, // 14: waddlemap.WaddleResponse.value_list:type_name -> waddlemap.ValueList
	2,  // 15: waddlemap.AddValueRequest.item:type_name -> waddlemap.DataItem
	2,  // 16: waddlemap.UpdateValueRequest.item:type_name -> waddlemap.DataItem
	2,  // 17: waddlemap.SearchResult.items:type_name -> waddlemap.DataItem
	2,  // 18: waddlemap.ValueList.items:type_name -> waddlemap.DataItem
	0,  // 19: waddlemap.WaddleService.Execute:input_type -> waddlemap.WaddleRequest
	1,  // 20: waddlemap.WaddleService.Execute:output_type -> waddlemap.WaddleResponse
	20, // [20:21] is the sub-list for method output_type
	19, // [19:20] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proto_waddle_protocol_proto_init() }
func file_proto_waddle_protocol_proto_init() {
	if File_proto_waddle_protocol_proto != nil {
		return
	}
	file_proto_waddle_protocol_proto_msgTypes[0].OneofWrappers = []any{
		(*WaddleRequest_CheckKey)(nil),
		(*WaddleRequest_GetVal)(nil),
		(*WaddleRequest_GetLen)(nil),
		(*WaddleRequest_GetLast)(nil),
		(*WaddleRequest_AddVal)(nil),
		(*WaddleRequest_SearchGlobal)(nil),
		(*WaddleRequest_SearchKey)(nil),
		(*WaddleRequest_Snapshot)(nil),
		(*WaddleRequest_UpdateVal)(nil),
		(*WaddleRequest_GetKeys)(nil),
		(*WaddleRequest_GetValList)(nil),
	}
	file_proto_waddle_protocol_proto_msgTypes[1].OneofWrappers = []any{
		(*WaddleResponse_Item)(nil),
		(*WaddleResponse_Length)(nil),
		(*WaddleResponse_SearchResults)(nil),
		(*WaddleResponse_KeyList)(nil),
		(*WaddleResponse_ValueList)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_waddle_protocol_proto_rawDesc), len(file_proto_waddle_protocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_waddle_protocol_proto_goTypes,
		DependencyIndexes: file_proto_waddle_protocol_proto_depIdxs,
		MessageInfos:      file_proto_waddle_protocol_proto_msgTypes,
	}.Build()
	File_proto_waddle_protocol_proto = out.File
	file_proto_waddle_protocol_proto_goTypes = nil
	file_proto_waddle_protocol_proto_depIdxs = nil
}
